inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance

inherit_gem:
  rubocop-rails:
    - config/default.yml
  rubocop-performance:
    - config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'